"""empty message

Revision ID: 1666a58346cf
Revises: 5f49fe971077
Create Date: 2024-12-19 00:11:08.477464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1666a58346cf'
down_revision = '5f49fe971077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_images')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['thumbnail'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('thumbnail')

    op.create_table('article_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('caption', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_images_article_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='article_images_pkey')
    )
    # ### end Alembic commands ###
