"""empty message

Revision ID: 5f49fe971077
Revises: c7e41dffd503
Create Date: 2024-12-18 01:52:29.988116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f49fe971077'
down_revision = 'c7e41dffd503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_categories', schema=None) as batch_op:
        batch_op.drop_constraint('article_categories_article_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'articles', ['article_id'], ['id'])

    with op.batch_alter_table('article_tags', schema=None) as batch_op:
        batch_op.drop_constraint('article_tags_article_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'articles', ['article_id'], ['id'])

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('approved_at')

    with op.batch_alter_table('article_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('article_tags_article_id_fkey', 'articles', ['article_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('article_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('article_categories_article_id_fkey', 'articles', ['article_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
