"""empty message

Revision ID: 978e15af4d23
Revises: 8203c497515b
Create Date: 2024-12-19 01:23:58.414805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978e15af4d23'
down_revision = '8203c497515b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint('articles_thumbnail_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_unique_constraint('articles_thumbnail_key', ['thumbnail'])

    # ### end Alembic commands ###
