"""Added is_approved row column and many to many category relationship

Revision ID: c7e41dffd503
Revises: 0baf73c03ce8
Create Date: 2024-12-04 01:46:00.511503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e41dffd503'
down_revision = '0baf73c03ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_categories',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'category_id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('articles_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('articles_category_id_fkey', 'categories', ['category_id'], ['id'])
        batch_op.drop_column('is_approved')

    op.drop_table('article_categories')
    # ### end Alembic commands ###
